import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      // colors: {
      //   background: "var(--background)",
      //   foreground: "var(--foreground)",
      //   primary: "var(--primary)",
      //   "primary-foreground": "var(--primary-foreground)",
      //   secondary: "var(--secondary)",
      //   "secondary-foreground": "var(--secondary-foreground)",
      //   muted: "var(--muted)",
      //   "muted-foreground": "var(--muted-foreground)",
      //   accent: "var(--accent)",
      //   "accent-foreground": "var(--accent-foreground)",
      //   card: "var(--card)",
      //   "card-foreground": "var(--card-foreground)",
      //   border: "var(--border)",
      //   input: "var(--input)",
      //   ring: "var(--ring)",
      // },
      // Finalized color variables
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        "hover-bg": "var(--hover-bg)",
        "hover-primary-bg": "var(--hover-primary-bg)",
        "hover-secondary-bg": "var(--hover-secondary-bg)",
        "shadow-small": "var(--shadow-small)",
        "shadow-medium": "var(--shadow-medium)",
        "shadow-large": "var(--shadow-large)",
        "secondary-text": "var(--secondary-text)",
        error: "var(--error)",
        "error-foreground": "var(--error-foreground)",
      },
    },
  },
  plugins: [],
} satisfies Config;
